apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: blockchain-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: blockchain-api
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  serviceClaims:
    - name: db
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: blockchain-database
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: Tanzu SEs
        system: Blockchain APIS
        description: This is a blockchain api
  source:
    git:
      ref:
        branch: main
      url: https://github.com/cdelashmutt-pivotal/blockchain-api
